version: '2'

services:
  db:
    image: postgres:9.5
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
      - ../database-initialization_files:/docker-entrypoint-initdb.d
      - ../../db_backups:/db_backups
  web:
    build: .
    restart: always
    environment:
       - DEVELOPMENT=1
    env_file:
       - ./config/db_variables.env
    command: bash /code/start_django_server.sh
    volumes:
      - ../cLIMS:/cLIMS
      - ../../media:/cLIMS/media
    ports:
      - "8000:8000"
    depends_on:
      - db
